# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Update warma.db

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
#  schedule:
#  - cron: '0 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pysqlite3
    
    - name: Git set
      run: |
        git config --global user.email "3244346642@qq.com"
        git config --global user.name "truebigsand"
    
    - name: Fetch data from Bilibili and insert to warma.db
      run: |
        python updater.py
    
    - name: Push to Github
      run: |
        git add warma.db
        git commit -m 'Update warma.db (auto from Github Actions)'
        git push -u origin master
